# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsNAQ-gPt7GaRiJp39qOPFU6r6VCy9zn
"""

# app.py
import streamlit as st
import pickle

st.title("📧 Email Spam Classifier")

# Load model and vectorizer
model = pickle.load(open("model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

message = st.text_area("Enter the email text:")

if st.button("Predict"):
    if message:
        data = vectorizer.transform([message])
        prediction = model.predict(data)[0]
        st.success("Prediction: 🚫 Spam" if prediction == "spam" else "✅ Ham")
    else:
        st.warning("Please enter some text.")