# -*- coding: utf-8 -*-
"""Spam Detection-Model training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgnI5Km2Rm_hKMUy77GoMXIE4p0dXDlN
"""

# train_model.py
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle

# Load and clean data
df = pd.read_csv("/content/spam.csv", encoding='ISO-8859-1')[['v1', 'v2']]
df.columns = ['label', 'message']

# Vectorize text
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['message'])
y = df['label']

# Train model
model = MultinomialNB()
model.fit(X, y)

# Save model and vectorizer
pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))